"""Upload API endpoints."""
import logging
from pathlib import Path
from uuid import UUID
from pathlib import Path
from fastapi import APIRouter, HTTPException, UploadFile, File
from fastapi.responses import FileResponse, JSONResponse
from app.models.upload import UploadResponse, CurrentMapResponse, MapMetadata
from app.services.map_processor import MapProcessor
from app.services.database_service import database_service
from app.services.storage_service import storage_service
from app.services.mqtt_service import mqtt_service
from app.config import settings

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/maps", tags=["maps"])
map_processor = MapProcessor()


@router.post("/upload", response_model=UploadResponse)
async def upload_map(file: UploadFile = File(...)):
    """
    Upload zip file (map output from Livo).
    
    Extract ZIP file, validate floorplan files, save PCD and floorplan images/metadata.
    ZIP must contain floorplan files generated by GUI (bag_mapping_tab.py).
    """
    try:
        # Validate file type
        if not file.filename.endswith('.zip'):
            raise HTTPException(status_code=400, detail="Only zip files are allowed")
        
        # Read file content
        file_content = await file.read()
        file_size = len(file_content)
        
        # Validate file size
        if file_size > settings.MAX_UPLOAD_SIZE:
            raise HTTPException(
                status_code=413,
                detail=f"File size exceeds maximum allowed size of {settings.MAX_UPLOAD_SIZE} bytes"
            )
        
        # Publish MQTT event: upload started
        mqtt_service.publish_map_event("map.upload.started", {
            "filename": file.filename,
            "size": file_size
        })
        
        # Check for old map and publish event if exists
        old_map = await database_service.get_current_map()
        if old_map and settings.SINGLE_VERSION_MODE:
            mqtt_service.publish_map_event("map.old.removed", {
                "previous_upload_id": old_map.get("upload_id"),
                "reason": "new_map_uploaded"
            })
        
        # Process upload (save file and metadata)
        result = await map_processor.process_upload(file_content, file.filename)
        if not result:
            raise HTTPException(status_code=500, detail="Failed to process upload")
        
        # Publish MQTT events
        mqtt_service.publish_map_event("map.upload.completed", {
            "upload_id": result["upload_id"],
            "filename": result["filename"],
            "size": result["size"]
        })
        
        if old_map and settings.SINGLE_VERSION_MODE:
            mqtt_service.publish_map_event("map.replaced", {
                "new_upload_id": result["upload_id"],
                "previous_upload_id": old_map.get("upload_id")
            })
        
        return UploadResponse(
            upload_id=UUID(result["upload_id"]),
            filename=result["filename"],
            status=result["status"],
            uploaded_at=result["uploaded_at"],
            size=result["size"],
            file_path=result["file_path"]
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error uploading map: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/current", response_model=CurrentMapResponse)
async def get_current_map():
    """Get current map (chỉ có 1 map duy nhất)."""
    try:
        map_doc = await database_service.get_current_map()
        if not map_doc:
            raise HTTPException(status_code=404, detail="No map found")
        
        return CurrentMapResponse(
            upload_id=UUID(map_doc["upload_id"]),
            filename=map_doc["filename"],
            status=map_doc["status"],
            metadata=MapMetadata(**map_doc["metadata"]),
            uploaded_at=map_doc["uploaded_at"],
            file_path=map_doc["file_path"],
            is_current=map_doc["is_current"],
            processed_at=map_doc.get("processed_at")
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error getting current map: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("", response_model=CurrentMapResponse)
async def get_maps():
    """Alias for /current (backward compatibility)."""
    return await get_current_map()


@router.get("/download")
async def download_current_map():
    """Tải file map (zip) hiện tại."""
    try:
        map_doc = await database_service.get_current_map()
        if not map_doc or not map_doc.get("file_path"):
            raise HTTPException(status_code=404, detail="No map found")
        
        file_path = Path(map_doc["file_path"])
        if not file_path.exists():
            raise HTTPException(status_code=404, detail="Map file not found on disk")
        
        return FileResponse(
            path=file_path,
            filename=file_path.name,
            media_type="application/zip"
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error downloading map: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.delete("/current")
async def delete_current_map():
    """Delete current map."""
    try:
        map_doc = await database_service.get_current_map()
        if not map_doc:
            raise HTTPException(status_code=404, detail="No map found")
        
        # Delete file
        if map_doc.get("file_path"):
            file_path = Path(map_doc["file_path"])
            storage_service.delete_file(file_path)
        
        # Delete processed files (images and metadata)
        metadata = map_doc.get("metadata", {})
        if metadata.get("image_paths"):
            for view_id, rel_path in metadata["image_paths"].items():
                image_path = storage_service.get_processed_path(rel_path)
                storage_service.delete_file(image_path)
        
        if metadata.get("metadata_path"):
            metadata_path = storage_service.get_processed_path(metadata["metadata_path"])
            storage_service.delete_file(metadata_path)
        
        # Delete PCD file
        if metadata.get("pcd_path"):
            pcd_path = Path(metadata["pcd_path"])
            storage_service.delete_file(pcd_path)
        
        # Delete from database
        success = await database_service.delete_current_map()
        if not success:
            raise HTTPException(status_code=500, detail="Failed to delete map")
        
        return {"success": True, "message": "Map deleted successfully"}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error deleting current map: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{upload_id}/metadata")
async def get_map_metadata(upload_id: UUID):
    """Get map metadata JSON for a specific upload."""
    try:
        map_doc = await database_service.get_map_by_upload_id(str(upload_id))
        if not map_doc:
            raise HTTPException(status_code=404, detail="Map not found")
        
        metadata_path = map_doc.get("metadata", {}).get("metadata_path")
        if not metadata_path:
            raise HTTPException(status_code=404, detail="Metadata not found")
        
        full_path = storage_service.get_processed_path(metadata_path)
        if not full_path.exists():
            raise HTTPException(status_code=404, detail="Metadata file not found")
        
        # Read and return JSON
        import json
        with open(full_path, 'r') as f:
            metadata = json.load(f)
        
        return JSONResponse(content=metadata)
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error getting map metadata: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{upload_id}/images/{view}")
async def get_map_image(upload_id: UUID, view: str):
    """Get map image for a specific view (top, side_x, side_y)."""
    try:
        if view not in ['top', 'side_x', 'side_y']:
            raise HTTPException(status_code=400, detail=f"Invalid view: {view}. Must be 'top', 'side_x', or 'side_y'")
        
        map_doc = await database_service.get_map_by_upload_id(str(upload_id))
        if not map_doc:
            raise HTTPException(status_code=404, detail="Map not found")
        
        image_paths = map_doc.get("metadata", {}).get("image_paths", {})
        if view not in image_paths:
            raise HTTPException(status_code=404, detail=f"Image for view '{view}' not found")
        
        rel_path = image_paths[view]
        full_path = storage_service.get_processed_path(rel_path)
        
        if not full_path.exists():
            raise HTTPException(status_code=404, detail="Image file not found")
        
        return FileResponse(
            path=str(full_path),
            media_type="image/png",
            filename=f"{upload_id}_{view}.png"
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error getting map image: {e}")
        raise HTTPException(status_code=500, detail=str(e))

