"""Upload API endpoints."""
import json
import logging
import re
import zipfile
import tempfile
import shutil
from datetime import datetime, timezone
from pathlib import Path
from uuid import UUID
from fastapi import APIRouter, HTTPException, UploadFile, File, BackgroundTasks, Form
from fastapi.responses import FileResponse, JSONResponse
from app.models.upload import UploadResponse, CurrentMapResponse, MapMetadata
from app.services.map_processor import MapProcessor
from app.services.database_service import database_service
from app.services.storage_service import storage_service
from app.services.mqtt_service import mqtt_service
from app.config import settings
from app.utils.time import ensure_utc, isoformat_utc, now_utc

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/maps", tags=["maps"])
map_processor = MapProcessor()


def _sanitize_filename_component(value: str) -> str:
    """Sanitize input to a filename-safe component."""
    safe_value = re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("_")
    return safe_value or "map"


def _format_iso_with_tz(dt: datetime) -> str:
    """
    Return ISO8601 string with timezone info in UTC.

    Contract: all timestamps written to metadata are stored as UTC.
    """
    return isoformat_utc(ensure_utc(dt))


def _write_metadata_file(
    map_name: str,
    vehicle_name: str,
    vehicle_id: str,
    size_bytes: int,
    created_at: datetime,
    uploaded_at: datetime,
) -> Path:
    """Write metadata JSON file (key-value) to storage directory."""
    storage_service.ensure_storage_directories()
    # Ngắn gọn: metadata_map (không kèm timestamp)
    filename = "metadata_map.json"
    metadata_path = storage_service.storage_dir / filename

    data = {
        "map_name": map_name,
        "vehicle_name": vehicle_name,
        "vehicle_id": vehicle_id,
        "size_bytes": size_bytes,
        "size_mb": round(size_bytes / 1024 / 1024, 2),
        "created_at": _format_iso_with_tz(created_at),
        "uploaded_at": _format_iso_with_tz(uploaded_at),
    }

    metadata_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    logger.info(f"Metadata file created at {metadata_path}")
    return metadata_path


@router.post("/upload", response_model=UploadResponse)
async def upload_map(
    file: UploadFile = File(...),
    map_name: str = Form(...),
    vehicle_id: str = Form(...)
):
    """
    Upload zip file (map output from Livo).
    
    Extract ZIP file, validate floorplan files, save PCD and floorplan images/metadata.
    ZIP must contain floorplan files generated by GUI (bag_mapping_tab.py).
    """
    try:
        map_name = (map_name or "").strip()
        vehicle_id = (vehicle_id or "").strip()

        if not map_name:
            raise HTTPException(status_code=400, detail="map_name is required")
        if not vehicle_id:
            raise HTTPException(status_code=400, detail="vehicle_id is required")

        vehicle = await database_service.get_vehicle(vehicle_id)
        if not vehicle:
            raise HTTPException(status_code=404, detail="Vehicle not found")
        vehicle_name = vehicle.get("name") or "Unknown"

        # Validate file type
        if not file.filename.endswith('.zip'):
            raise HTTPException(status_code=400, detail="Only zip files are allowed")
        
        # Read file content
        file_content = await file.read()
        file_size = len(file_content)
        
        # Validate file size
        if file_size > settings.MAX_UPLOAD_SIZE:
            raise HTTPException(
                status_code=413,
                detail=f"File size exceeds maximum allowed size of {settings.MAX_UPLOAD_SIZE} bytes"
            )
        
        # Publish MQTT event: upload started
        mqtt_service.publish_map_event("map.upload.started", {
            "filename": file.filename,
            "size": file_size
        })
        
        # Check for old map and publish event if exists
        old_map = await database_service.get_current_map()
        if old_map and settings.SINGLE_VERSION_MODE:
            mqtt_service.publish_map_event("map.old.removed", {
                "previous_upload_id": old_map.get("upload_id"),
                "reason": "new_map_uploaded"
            })
        
        # Process upload (save file, extract to storage, and save metadata)
        logger.info("=" * 60)
        logger.info(f"📤 Processing upload: {file.filename} ({file_size / 1024 / 1024:.2f} MB)")
        logger.info("=" * 60)
        result = await map_processor.process_upload(file_content, file.filename)
        if not result:
            logger.error("❌ Upload processing failed - no result returned")
            raise HTTPException(
                status_code=500, 
                detail="Failed to process upload. Check server logs for details."
            )
        
        # Verify extraction was successful
        logger.info("🔍 Verifying storage extraction...")
        storage_paths = result.get("metadata", {}).get("storage_paths", {})
        if storage_paths:
            logger.info(f"✅ Verified: {len(storage_paths)} items extracted to storage")
            for key, path in storage_paths.items():
                logger.info(f"   - {key}: {path}")
        else:
            logger.warning("⚠️ No storage_paths in result metadata")
        
        logger.info("=" * 60)
        logger.info(f"✅ Upload and extraction completed successfully!")
        logger.info(f"   Upload ID: {result['upload_id']}")
        logger.info("=" * 60)
        
        # Publish MQTT events
        mqtt_service.publish_map_event("map.upload.completed", {
            "upload_id": result["upload_id"],
            "filename": result["filename"],
            "size": result["size"]
        })
        
        if old_map and settings.SINGLE_VERSION_MODE:
            mqtt_service.publish_map_event("map.replaced", {
                "new_upload_id": result["upload_id"],
                "previous_upload_id": old_map.get("upload_id")
            })

        # Create metadata txt file and persist extended metadata
        try:
            file_stat = Path(result["file_path"]).stat()
            # Interpret mtime as an absolute instant and convert to UTC-aware datetime.
            # Using tz=UTC ensures we don't accidentally treat a local naive datetime as UTC.
            created_at_local = datetime.fromtimestamp(file_stat.st_mtime, tz=timezone.utc)
        except Exception as stat_error:
            logger.warning(f"Could not read file timestamps: {stat_error}")
            created_at_local = now_utc()

        # Use canonical UTC for upload time
        uploaded_at_local = now_utc()
        metadata_json_path = _write_metadata_file(
            map_name=map_name,
            vehicle_name=vehicle_name,
            vehicle_id=vehicle_id,
            size_bytes=result["size"],
            created_at=created_at_local,
            uploaded_at=uploaded_at_local,
        )

        extended_metadata = {
            "map_name": map_name,
            "vehicle_id": vehicle_id,
            "vehicle_name": vehicle_name,
            "metadata_json_path": str(metadata_json_path),
            "file_created_at": _format_iso_with_tz(created_at_local),
            "file_uploaded_at": _format_iso_with_tz(uploaded_at_local),
        }

        if "metadata" in result and isinstance(result["metadata"], dict):
            result["metadata"].update(extended_metadata)

        update_payload = {
            "metadata": result.get("metadata", {}),
            "map_name": map_name,
            "vehicle_id": vehicle_id,
            "vehicle_name": vehicle_name,
        }
        updated = await database_service.update_map(result["upload_id"], update_payload)
        if not updated:
            logger.warning("Failed to update map document with extended metadata")
        
        return UploadResponse(
            upload_id=UUID(result["upload_id"]),
            filename=result["filename"],
            status=result["status"],
            uploaded_at=result["uploaded_at"],
            size=result["size"],
            file_path=result["file_path"]
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error uploading map: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/current", response_model=CurrentMapResponse)
async def get_current_map():
    """Get current map (chỉ có 1 map duy nhất)."""
    try:
        map_doc = await database_service.get_current_map()
        if not map_doc:
            raise HTTPException(status_code=404, detail="No map found")
        
        return CurrentMapResponse(
            upload_id=UUID(map_doc["upload_id"]),
            filename=map_doc["filename"],
            status=map_doc["status"],
            metadata=MapMetadata(**map_doc["metadata"]),
            uploaded_at=map_doc["uploaded_at"],
            file_path=map_doc["file_path"],
            is_current=map_doc["is_current"],
            processed_at=map_doc.get("processed_at")
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error getting current map: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("", response_model=CurrentMapResponse)
async def get_maps():
    """Alias for /current (backward compatibility)."""
    return await get_current_map()


@router.get("/download")
async def download_current_map():
    """Tải file map (zip) hiện tại."""
    try:
        map_doc = await database_service.get_current_map()
        if not map_doc or not map_doc.get("file_path"):
            raise HTTPException(status_code=404, detail="No map found")
        
        file_path = Path(map_doc["file_path"])
        if not file_path.exists():
            raise HTTPException(status_code=404, detail="Map file not found on disk")
        
        return FileResponse(
            path=file_path,
            filename=file_path.name,
            media_type="application/zip"
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error downloading map: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.delete("/current")
async def delete_current_map():
    """Delete current map."""
    try:
        map_doc = await database_service.get_current_map()
        if not map_doc:
            raise HTTPException(status_code=404, detail="No map found")
        
        # Delete file
        if map_doc.get("file_path"):
            file_path = Path(map_doc["file_path"])
            storage_service.delete_file(file_path)
        
        # Delete processed files (images and metadata)
        metadata = map_doc.get("metadata", {})
        if metadata.get("image_paths"):
            for view_id, rel_path in metadata["image_paths"].items():
                image_path = storage_service.get_processed_path(rel_path)
                storage_service.delete_file(image_path)
        
        if metadata.get("metadata_path"):
            metadata_path = storage_service.get_processed_path(metadata["metadata_path"])
            storage_service.delete_file(metadata_path)
        
        # Delete PCD file
        if metadata.get("pcd_path"):
            pcd_path = Path(metadata["pcd_path"])
            storage_service.delete_file(pcd_path)
        
        # Cleanup storage directory
        storage_service.cleanup_storage()
        
        # Delete from database
        success = await database_service.delete_current_map()
        if not success:
            raise HTTPException(status_code=500, detail="Failed to delete map")
        
        return {"success": True, "message": "Map deleted successfully"}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error deleting current map: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ========== Localization APIs ==========

@router.post("/extract")
async def extract_current_map():
    """Manually trigger extraction of current map zip file to storage."""
    try:
        # Get current map
        map_doc = await database_service.get_current_map()
        if not map_doc or not map_doc.get("file_path"):
            raise HTTPException(status_code=404, detail="No map found")
        
        file_path = Path(map_doc["file_path"])
        if not file_path.exists():
            raise HTTPException(status_code=404, detail="Map file not found on disk")
        
        if not file_path.name.endswith('.zip'):
            raise HTTPException(status_code=400, detail="Current map is not a ZIP file")
        
        logger.info("=" * 60)
        logger.info(f"🔄 MANUAL EXTRACTION TRIGGERED")
        logger.info(f"   File: {file_path.name}")
        logger.info("=" * 60)
        
        # Use extract_zip_to_storage to avoid re-processing metadata
        result = await map_processor.extract_zip_to_storage(file_path)
        
        if not result:
            raise HTTPException(
                status_code=500,
                detail="Failed to extract map. Check server logs for details."
            )
        
        # Verify extraction
        storage_paths = result.get("metadata", {}).get("storage_paths", {})
        
        return JSONResponse(content={
            "success": True,
            "message": "Map extracted successfully",
            "upload_id": result["upload_id"],
            "extracted_items": len(storage_paths),
            "storage_paths": storage_paths
        })
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error extracting map: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/storage/status")
async def get_storage_status():
    """Check storage status and list extracted files."""
    try:
        status = {
            "storage_dir": str(storage_service.storage_dir),
            "exists": storage_service.storage_dir.exists(),
            "folders": {}
        }
        
        if status["exists"]:
            for folder in ["merged_map", "fastloc_map", "floorplan_2d"]:
                folder_path = storage_service.get_storage_path(folder)
                if folder_path.exists():
                    files = list(folder_path.rglob("*"))
                    files = [f for f in files if f.is_file()]
                    status["folders"][folder] = {
                        "exists": True,
                        "file_count": len(files),
                        "files": [f.name for f in files[:10]]  # First 10 files
                    }
                else:
                    status["folders"][folder] = {"exists": False, "file_count": 0}
            
            qr_file = storage_service.get_storage_path("QR_detect.json")
            status["qr_detect"] = {
                "exists": qr_file.exists(),
                "path": str(qr_file) if qr_file.exists() else None
            }
        
        return JSONResponse(content=status)
    except Exception as e:
        logger.error(f"Error getting storage status: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/localization/qr")
async def download_qr_code():
    """Download QR_detect.json for localization."""
    try:
        qr_path = storage_service.get_storage_path("QR_detect.json")
        if not qr_path.exists():
            raise HTTPException(status_code=404, detail="QR_detect.json not found")
        
        return FileResponse(
            path=str(qr_path),
            filename="QR_detect.json",
            media_type="application/json"
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error downloading QR code: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/localization/fastloc/download")
async def download_fastloc_folder(background_tasks: BackgroundTasks):
    """Download entire fastloc_map folder as zip file."""
    temp_zip_path = None
    try:
        fastloc_dir = storage_service.get_storage_path("fastloc_map")
        if not fastloc_dir.exists():
            raise HTTPException(status_code=404, detail="fastloc_map folder not found")
        
        # Check if folder has any files
        files = list(fastloc_dir.iterdir())
        if not files or all(f.is_dir() for f in files):
            raise HTTPException(status_code=404, detail="fastloc_map folder is empty")
        
        # Create temporary zip file
        temp_zip = tempfile.NamedTemporaryFile(delete=False, suffix='.zip')
        temp_zip_path = Path(temp_zip.name)
        temp_zip.close()
        
        # Create zip file
        with zipfile.ZipFile(temp_zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for file_path in fastloc_dir.rglob('*'):
                if file_path.is_file():
                    # Get relative path from fastloc_dir
                    arcname = file_path.relative_to(fastloc_dir)
                    zipf.write(file_path, arcname)
                    logger.debug(f"Added to zip: {arcname}")
        
        # Schedule cleanup after response
        background_tasks.add_task(cleanup_temp_file, temp_zip_path)
        
        # Return zip file
        return FileResponse(
            path=str(temp_zip_path),
            filename="fastloc_map.zip",
            media_type="application/zip"
        )
    except HTTPException:
        if temp_zip_path and temp_zip_path.exists():
            temp_zip_path.unlink()
        raise
    except Exception as e:
        if temp_zip_path and temp_zip_path.exists():
            temp_zip_path.unlink()
        logger.error(f"Error downloading fastloc folder: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ========== Web PCD APIs ==========

@router.get("/web/merged")
async def download_merged_pcd():
    """Download merged_all.pcd for web viewer."""
    try:
        merged_pcd = storage_service.get_storage_path("merged_map", "merged_all.pcd")
        if not merged_pcd.exists():
            raise HTTPException(status_code=404, detail="merged_all.pcd not found")
        
        return FileResponse(
            path=str(merged_pcd),
            filename="merged_all.pcd",
            media_type="application/octet-stream"
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error downloading merged PCD: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ========== Floorplan 2D APIs ==========

@router.get("/floorplan/download")
async def download_floorplan_folder(background_tasks: BackgroundTasks):
    """Download entire floorplan_2d folder as zip file."""
    temp_zip_path = None
    try:
        floorplan_dir = storage_service.get_storage_path("floorplan_2d")
        if not floorplan_dir.exists():
            raise HTTPException(status_code=404, detail="floorplan_2d folder not found")
        
        # Check if folder has any files
        files = list(floorplan_dir.iterdir())
        if not files or all(f.is_dir() for f in files):
            raise HTTPException(status_code=404, detail="floorplan_2d folder is empty")
        
        # Create temporary zip file
        temp_zip = tempfile.NamedTemporaryFile(delete=False, suffix='.zip')
        temp_zip_path = Path(temp_zip.name)
        temp_zip.close()
        
        # Create zip file
        with zipfile.ZipFile(temp_zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for file_path in floorplan_dir.rglob('*'):
                if file_path.is_file():
                    # Get relative path from floorplan_dir
                    arcname = file_path.relative_to(floorplan_dir)
                    zipf.write(file_path, arcname)
                    logger.debug(f"Added to zip: {arcname}")
        
        # Schedule cleanup after response
        background_tasks.add_task(cleanup_temp_file, temp_zip_path)
        
        # Return zip file
        return FileResponse(
            path=str(temp_zip_path),
            filename="floorplan_2d.zip",
            media_type="application/zip"
        )
    except HTTPException:
        if temp_zip_path and temp_zip_path.exists():
            temp_zip_path.unlink()
        raise
    except Exception as e:
        if temp_zip_path and temp_zip_path.exists():
            temp_zip_path.unlink()
        logger.error(f"Error downloading floorplan folder: {e}")
        raise HTTPException(status_code=500, detail=str(e))


def cleanup_temp_file(file_path: Path):
    """Cleanup temporary file."""
    try:
        if file_path.exists():
            file_path.unlink()
            logger.debug(f"Cleaned up temporary file: {file_path}")
    except Exception as e:
        logger.warning(f"Error cleaning up temporary file {file_path}: {e}")

