import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'vi' | 'ja' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations = {
  vi: {
    'language': 'Ngôn ngữ',
    'vehicles': 'Phương tiện',
    'about': 'Giới thiệu',
    'map': 'Theo dõi',
    'user': 'Người dùng',
    'switch_language': 'Chuyển đổi ngôn ngữ',
    'help': 'Trợ giúp',
    // Vehicles page translations
    'vehicle_list': 'Danh sách phương tiện',
    'vehicle_management': 'Quản lý các xe thi công đào hầm',
    'total_vehicles': 'Tổng phương tiện',
    'active_vehicles': 'Đang hoạt động',
    'maintenance': 'Bảo trì',
    'issues': 'Sự cố',
    'license_plate': 'Biển số máy',
    'driver': 'Tài xế',
    'vehicle_type': 'Vai trò',
    'vehicle_type_label': 'Vai trò:',
    'vehicle_category': 'Phân loại thiết bị',
    'equipment_category_label': 'Phân loại thiết bị:',
    'vehicle_type_unknown': 'Chưa xác định',
    'mission': 'Nhiệm vụ',
    'status': 'Trạng thái',
    'actions': 'Thao tác',
    'active': 'Hoạt động',
    'online': 'Trực tuyến',
    'offline': 'Ngoại tuyến',
    'offline_vehicles': 'Phương tiện ngoại tuyến',
    'offline_vehicles_count': 'Ngoại tuyến',
    'license_plate_required': 'Biển số máy là bắt buộc',
    'driver_required': 'Tên tài xế là bắt buộc',
    'vehicle_type_required': 'Loại xe là bắt buộc',
    'mission_required': 'Nhiệm vụ là bắt buộc',
    'select_vehicle_type': 'Chọn loại xe',
    'select_mission': 'Chọn nhiệm vụ',
    'cancel': 'Hủy',
    'inactive': 'Không hoạt động',
    'driver_placeholder': 'Họ và tên tài xế',
    // Vehicle types
    'tbm_tunnel': 'Xe đào hầm TBM',
    'transport_vehicle': 'Xe vận chuyển',
    'concrete_pump': 'Xe bơm bê tông',
    'crane': 'Xe cẩu',
    'loader': 'Xe xúc lật',
    'truck': 'Xe tải',
    'other_specialized': 'Xe chuyên dụng khác',
    // Mission types
    'tunnel_line_1': 'Đào hầm tuyến 1',
    'tunnel_line_2': 'Đào hầm tuyến 2',
    'material_transport': 'Vận chuyển vật liệu',
    'concrete_wall_pump': 'Bơm bê tông tường hầm',
    'soil_transport': 'Vận chuyển đất đá',
    'equipment_installation': 'Lắp đặt thiết bị',
    'tunnel_maintenance': 'Bảo trì đường hầm',
    'geological_survey': 'Khảo sát địa chất',
    'other_mission': 'Nhiệm vụ khác',
    // VehicleMap page translations
    'vehicle_map_3d': 'Bản đồ 3D phương tiện',
    'track_real_time': 'Theo dõi vị trí real-time các phương tiện trong đường hầm',
    'fullscreen': 'Toàn màn hình',
    'exit_fullscreen': 'Thoát toàn màn hình',
    'vehicle_list_title': 'Danh sách phương tiện',
    'filter_vehicles': 'Lọc phương tiện',
    'search_vehicle': 'Tìm kiếm phương tiện...',
    'active_vehicles_count': 'Đang hoạt động',
    'maintenance_vehicles_count': 'Bảo trì',
    'inactive_vehicles_count': 'Không hoạt động',
    'total_vehicles_count': 'Tổng phương tiện',
    'legend': 'Chú thích',
    'vehicle_info': 'Thông tin phương tiện',
    'vehicle_details': 'Thông tin xe',
    'license_plate_label': 'Biển số:',
    'vehicle_type_label': 'Vai trò:',
    'status_label': 'Trạng thái:',
    'driver_info': 'Tài xế vận hành',
    'driver_name': 'Họ tên:',
    'id_label': 'ID:',
    'mission_type': 'Loại nhiệm vụ',
    'mission_label': 'Nhiệm vụ:',
    'position_time': 'Vị trí & Thời gian',
    'coordinates': 'Tọa độ:',
    'update_time': 'Cập nhật:',
    'focus_camera': 'Focus Camera',
    'deselect': 'Bỏ chọn',
    'filter_applied': 'Bộ lọc đang áp dụng:',
    'clear_all': 'Xóa tất cả',
    'status_filter': 'Trạng thái:',
    'vehicle_type_filter': 'Vai trò:',
    'mission_filter': 'Nhiệm vụ:',
    'filter_popup_title': 'Lọc phương tiện',
    'all': 'Tất cả',
    'clear_filter': 'Xóa bộ lọc',
    'apply_filter': 'Áp dụng',
    'guide_text': 'Hướng dẫn: Chọn phương tiện từ danh sách bên phải hoặc click trực tiếp vào phương tiện trong bản đồ',
    'guide_text_2d': '2D',
    'guide_text_3d': '3D',
    'guide_text_end': 'để xem thông tin chi tiết. Sử dụng nút chuyển đổi 2D/3D để thay đổi góc nhìn.',
    'driver_label': 'Tài xế:',
    'type_label': 'Loại:',
    'mission_label_short': 'Nhiệm vụ:',
    'status_label_short': 'Trạng thái:',
    'update_label': 'Cập nhật:',
    // Driver names
    'driver_name_1': 'Nguyễn Văn A',
    'driver_name_2': 'Trần Thị B',
    'driver_name_3': 'Lê Văn C',
    'driver_name_4': 'Phạm Văn D',
    // EditVehicle page translations
    'edit_vehicle_title': 'Chỉnh sửa phương tiện',
    'update_vehicle_info': 'Cập nhật thông tin phương tiện thi công',
    'vehicle_not_found': 'Không tìm thấy phương tiện!',
    'update_success': 'Cập nhật phương tiện thành công!',
    'update_button': 'Cập nhật',
    // About page translations
    'about_hero_title': 'Hệ thống theo dõi vị trí xe NishioT&M',
    'about_hero_desc': 'Hệ thống quản lý và theo dõi phương tiện trong môi trường không thể sử dụng GPS, GNSS như đường hầm và khai thác mỏ. Hệ thống này có thể theo dõi thời gian thực, xác nhận tình trạng vận hành của phương tiện và quản lý vị trí phương tiện một cách chi tiết.',
    'about_video_title': 'Giới thiệu dự án',
    'about_video_desc': 'Xem video demo để hiểu rõ hơn về dự án',
    'about_video_alt': 'Trình duyệt của bạn không hỗ trợ video.',
    'about_mission_title': 'Sứ mệnh của chúng tôi',
    'about_mission_desc': 'Chúng tôi có thể cung cấp giải pháp công nghệ toàn diện cho quản lý và theo dõi phương tiện trong môi trường không thể sử dụng GPS, GNSS như đường hầm và khai thác mỏ.',
    'about_mission_1': 'Thực hiện tối ưu hóa an toàn, hiệu quả và quy trình vận hành',
    'about_mission_2': 'Tối ưu hiệu quả vận hành',
    'about_mission_3': 'Giảm thiểu rủi ro và sự cố',
    'about_mission_safety': 'An toàn & Hiệu quả',
    // Login page translations
    'login_to_vehicles': 'Đăng nhập vào hệ thống xe',
    'enter_password_to_access': 'Nhập mật khẩu để truy cập',
    'password': 'Mật khẩu',
    'enter_password': 'Nhập mật khẩu',
    'incorrect_password': 'Mật khẩu không đúng',
    'login': 'Đăng nhập',
    'logging_in': 'Đang đăng nhập...',
    'default_password': 'Mật khẩu mặc định',
    'logout': 'Đăng xuất',
    // Upload page
    'upload_menu_label': 'Upload',
    'upload_page_title': 'Upload bản đồ từ file ZIP',
    'upload_page_desc': 'Tải lên gói dữ liệu đã quét (PCD, ảnh 2D, danh sách QRCode) để xem và kiểm tra trước khi sử dụng.',
    'upload_zip_title': 'Upload file ZIP bản đồ',
    'upload_pcd_preview_title': 'Preview PCD',
    'upload_pcd_preview_mock': 'PCD Preview - Dữ liệu sẽ hiển thị khi bạn load ZIP gần nhất.',
    'upload_image_preview_title': 'Preview ảnh 2D',
    'upload_image_preview_mock': 'Image 2D Preview - Dữ liệu sẽ hiển thị khi bạn load ZIP gần nhất.',
    'upload_qr_list_title': 'Danh sách QRCode',
    'upload_qr_list_desc': 'Danh sách QRCode được trích xuất giả lập từ dữ liệu ZIP. Mỗi QRCode gắn với một vị trí trong đường hầm.',
    'upload_qr_code': 'QRCode',
    'upload_qr_position': 'Vị trí',
    'upload_qr_empty': 'Chưa có QRCode nào trong danh sách.',
    'upload_qr_add_new': 'Thêm mới dữ liệu',
    'upload_qr_save': 'Lưu',
    'upload_qr_cancel': 'Hủy',
    'upload_qr_index_label': 'Index',
    'upload_qr_index_placeholder': '000-999',
    'upload_qr_index_duplicate': 'Index này đã tồn tại',
    'upload_qr_index_invalid': 'Index phải là số từ 000 đến 999',
    'upload_qr_position_x': 'X',
    'upload_qr_position_y': 'Y',
    'upload_qr_position_z': 'Z',
    'upload_qr_position_invalid': 'Vị trí không hợp lệ',
    'upload_qr_pick_position': 'Chọn vị trí',
    'upload_qr_pick_active': 'Đang chọn trên bản đồ...',
    'upload_qr_pick_done': 'Thoát chọn',
    'upload_qr_pick_hint': 'Click trên bản đồ 2D để thả pin. Bạn có thể click nhiều lần cho tới khi thoát chế độ chọn.',
    'upload_qr_pick_overlay': 'Đang bật chế độ chọn vị trí. Các khu vực khác đang được khoá.',
    'upload_qr_actions': 'Thao tác',
    'upload_qr_edit': 'Chỉnh sửa',
    'upload_qr_delete': 'Xóa',
    'upload_qr_delete_confirm': 'Bạn có chắc chắn muốn xóa QR code này?',
    'upload_qr_save_changes': 'Lưu',
    'upload_qr_cancel_edit': 'Hủy',
    'upload_qr_edit_position': 'Chỉnh sửa vị trí',
    // Map info translations
    'map_info_title': 'Thông tin bản đồ',
    'map_name': 'Tên bản đồ',
    'map_created_at': 'Ngày tạo',
    'map_uploaded_by': 'Người tải lên',
    'map_uploaded_at': 'Ngày tải lên',
    'map_file_size': 'Dung lượng',
    // QR Code descriptions
    'qr_desc_tunnel_start': 'Điểm mốc đầu đường hầm',
    'qr_desc_tunnel_mid': 'Điểm mốc giữa đường hầm',
    'qr_desc_maintenance_area': 'Khu vực bảo trì thiết bị',
    // QR Generator page
    'qr_generator_menu_label': 'Tạo QR Code',
    'qr_generator_title': 'Tạo QR Code',
    'qr_generator_desc': '',
    'qr_generator_index_label': 'Nhập index',
    'qr_generator_index_placeholder': 'Nhập số từ 0 đến 999',
    'qr_generator_index_invalid': 'Vui lòng nhập số hợp lệ từ 0 đến 999',
    'qr_generator_create_button': 'Tạo QR Code',
    'qr_generator_preview_title': 'Preview QR Code',
    'qr_generator_no_qr': 'Chưa có QR Code nào được tạo. Vui lòng nhập index và nhấn "Tạo QR Code".',
    'qr_generator_download_png': 'Tải về PNG',
    'qr_generator_copy_clipboard': 'Copy vào Clipboard',
    'qr_generator_copy_success': 'Đã copy QR Code vào clipboard thành công!',
    'qr_generator_copy_error': 'Lỗi khi copy QR Code vào clipboard',
    'qr_generator_reset': 'Reset',
    'qr_generator_qr_content': 'Nội dung QR Code',
    // Health page translations
    'health_title': 'Health Check',
    'health_description': 'Kiểm tra trạng thái của frontend và backend services',
    'health_menu_label': 'Health',
    'frontend_health': 'Frontend Health',
    'backend_health': 'Backend Health',
    'backend_services': 'Backend Services',
    'refresh': 'Làm mới',
    'checking': 'Đang kiểm tra',
    'degraded': 'Suy giảm',
    'unhealthy': 'Không khỏe mạnh',
    'version': 'Phiên bản',
    'url': 'URL',
    'service': 'Dịch vụ',
    'uptime': 'Thời gian hoạt động',
    'latency': 'Độ trễ',
    'broker': 'Broker',
    'last_updated': 'Cập nhật lần cuối',
    // PCD Clipping translations
    'pcd_adjust_point_cloud': 'Điều chỉnh Point Cloud',
    'pcd_close': 'Đóng',
    'pcd_show_adjust': 'Hiển thị điều chỉnh Point Cloud',
    'pcd_adjust': 'Điều chỉnh PCD',
    'pcd_loading': 'Đang tải dữ liệu point cloud...',
    'pcd_adjust_display_area': 'Điều chỉnh vùng hiển thị',
    'pcd_slider_hint': 'Kéo slider để cắt point cloud theo các trục X, Y, Z',
    'pcd_axis_x': 'Trục X:',
    'pcd_axis_y': 'Trục Y:',
    'pcd_axis_z': 'Trục Z:',
    'pcd_value': 'Giá trị:',
    'pcd_to': 'đến',
    'pcd_bounds_x': 'Bounds X:',
    'pcd_bounds_y': 'Bounds Y:',
    'pcd_bounds_z': 'Bounds Z:',
    'pcd_no_pcd_available': 'Không có PCD nào',
    'pcd_x_range': 'X Range:',
    'pcd_y_range': 'Y Range:',
    'pcd_z_range': 'Z Range:',
    'pcd_points_rendered': 'points rendered',
    'pcd_bounds': 'Bounds:',
    'pcd_current_range': 'Current Range:',
    'pcd_loading_point_cloud': 'Loading point cloud...',
    'pcd_no_data': 'No point cloud data',
    'pcd_current_viewing_title': 'Đang xem PCD',
    'pcd_uploaded_by': 'Người tải lên',
    'pcd_size': 'Dung lượng',
    'pcd_id': 'ID',
    'loading_pcd': 'Đang tải PCD...',
    'pcd_loaded': 'Đã tải PCD',
    'no_pcd_loaded': 'Chưa có dữ liệu point cloud',
  },
  en: {
    'language': 'Language',
    'vehicles': 'Vehicles',
    'about': 'About',
    'map': 'Tracking',
    'user': 'User',
    'switch_language': 'Switch language',
    'help': 'Help',
    // Vehicles page translations
    'vehicle_list': 'Vehicle list',
    'vehicle_management': 'Construction vehicle management for tunnel excavation',
    'total_vehicles': 'Total vehicles',
    'active_vehicles': 'Active',
    'maintenance': 'Maintenance',
    'issues': 'Issues',
    'license_plate': 'Machine plate number',
    'driver': 'Driver',
    'vehicle_type': 'Role',
    'vehicle_type_label': 'Role:',
    'vehicle_category': 'Equipment Category',
    'equipment_category_label': 'Equipment Category:',
    'vehicle_type_unknown': 'Unknown',
    'mission': 'Mission',
    'status': 'Status',
    'actions': 'Actions',
    'active': 'Active',
    'online': 'Online',
    'offline': 'Offline',
    'offline_vehicles': 'Offline vehicles',
    'offline_vehicles_count': 'Offline',
    'license_plate_required': 'License plate is required',
    'driver_required': 'Driver name is required',
    'vehicle_type_required': 'Vehicle type is required',
    'mission_required': 'Mission is required',
    'select_vehicle_type': 'Select vehicle type',
    'select_mission': 'Select mission',
    'cancel': 'Cancel',
    'inactive': 'Inactive',
    'driver_placeholder': 'Driver full name',
    // Vehicle types
    'tbm_tunnel': 'TBM tunnel excavator',
    'transport_vehicle': 'Transport vehicle',
    'concrete_pump': 'Concrete pump',
    'crane': 'Crane truck',
    'loader': 'Loader',
    'truck': 'Truck',
    'other_specialized': 'Other specialized vehicle',
    // Mission types
    'tunnel_line_1': 'Tunnel excavation line 1',
    'tunnel_line_2': 'Tunnel excavation line 2',
    'material_transport': 'Material transport',
    'concrete_wall_pump': 'Tunnel wall concrete pumping',
    'soil_transport': 'Soil and rock transport',
    'equipment_installation': 'Equipment installation',
    'tunnel_maintenance': 'Tunnel maintenance',
    'geological_survey': 'Geological survey',
    'other_mission': 'Other mission',
    // VehicleMap page translations
    'vehicle_map_3d': '3D vehicle map',
    'track_real_time': 'Track real-time positions of vehicles inside the tunnel',
    'fullscreen': 'Fullscreen',
    'exit_fullscreen': 'Exit fullscreen',
    'vehicle_list_title': 'Vehicle list',
    'filter_vehicles': 'Filter vehicles',
    'search_vehicle': 'Search vehicles...',
    'active_vehicles_count': 'Active',
    'maintenance_vehicles_count': 'Maintenance',
    'inactive_vehicles_count': 'Inactive',
    'total_vehicles_count': 'Total vehicles',
    'legend': 'Legend',
    'vehicle_info': 'Vehicle information',
    'vehicle_details': 'Vehicle details',
    'license_plate_label': 'Plate:',
    'vehicle_type_label': 'Role:',
    'status_label': 'Status:',
    'driver_info': 'Driver',
    'driver_name': 'Name:',
    'id_label': 'ID:',
    'mission_type': 'Mission type',
    'mission_label': 'Mission:',
    'position_time': 'Position & Time',
    'coordinates': 'Coordinates:',
    'update_time': 'Updated:',
    'focus_camera': 'Focus camera',
    'deselect': 'Deselect',
    'filter_applied': 'Applied filters:',
    'clear_all': 'Clear all',
    'status_filter': 'Status:',
    'vehicle_type_filter': 'Role:',
    'mission_filter': 'Mission:',
    'filter_popup_title': 'Filter vehicles',
    'all': 'All',
    'clear_filter': 'Clear filter',
    'apply_filter': 'Apply',
    'guide_text': 'Guide: Select a vehicle from the list on the right or click directly on a vehicle in the map in',
    'guide_text_2d': '2D',
    'guide_text_3d': '3D',
    'guide_text_end': 'mode to see details. Use the 2D/3D toggle to change the view.',
    'driver_label': 'Driver:',
    'type_label': 'Type:',
    'mission_label_short': 'Mission:',
    'status_label_short': 'Status:',
    'update_label': 'Updated:',
    // Driver names
    'driver_name_1': 'Nguyen Van A',
    'driver_name_2': 'Tran Thi B',
    'driver_name_3': 'Le Van C',
    'driver_name_4': 'Pham Van D',
    // EditVehicle page translations
    'edit_vehicle_title': 'Edit vehicle',
    'update_vehicle_info': 'Update construction vehicle information',
    'vehicle_not_found': 'Vehicle not found!',
    'update_success': 'Vehicle updated successfully!',
    'update_button': 'Update',
    // About page translations
    'about_hero_title': 'NishioT&M vehicle tracking system',
    'about_hero_desc': 'A system for managing and tracking vehicles in environments where GPS/GNSS cannot be used such as tunnels and mines. It supports real-time tracking, operation status checking, and detailed vehicle position management.',
    'about_video_title': 'Project introduction',
    'about_video_desc': 'Watch the demo video to understand the project better',
    'about_video_alt': 'Your browser does not support video.',
    'about_mission_title': 'Our mission',
    'about_mission_desc': 'We provide a comprehensive technology solution for managing and tracking vehicles in environments where GPS/GNSS cannot be used.',
    'about_mission_1': 'Optimize safety, efficiency and operation processes',
    'about_mission_2': 'Optimize operational efficiency',
    'about_mission_3': 'Minimize risks and incidents',
    'about_mission_safety': 'Safety & Efficiency',
    // Login page translations
    'login_to_vehicles': 'Login to vehicle system',
    'enter_password_to_access': 'Enter password to access',
    'password': 'Password',
    'enter_password': 'Enter password',
    'incorrect_password': 'Incorrect password',
    'login': 'Login',
    'logging_in': 'Logging in...',
    'default_password': 'Default password',
    'logout': 'Logout',
    // Upload page
    'upload_menu_label': 'Upload',
    'upload_page_title': 'Upload map from ZIP file',
    'upload_page_desc': 'Upload scanned data package (PCD, 2D images, QRCode list) to preview and verify before using.',
    'upload_zip_title': 'Upload map ZIP file',
    'upload_pcd_preview_title': 'PCD preview',
    'upload_pcd_preview_mock': 'PCD Preview - Data will appear when you load the latest ZIP.',
    'upload_image_preview_title': '2D image preview',
    'upload_image_preview_mock': '2D Image Preview - Data will appear when you load the latest ZIP.',
    'upload_qr_list_title': 'QRCode list',
    'upload_qr_list_desc': 'Simulated list of QRCodes extracted from the ZIP. Each QRCode is linked to a position in the tunnel.',
    'upload_qr_code': 'QRCode',
    'upload_qr_position': 'Position',
    'upload_qr_empty': 'No QRCode in the list yet.',
    'upload_qr_add_new': 'Add new',
    'upload_qr_save': 'Save',
    'upload_qr_cancel': 'Cancel',
    'upload_qr_index_label': 'Index',
    'upload_qr_index_placeholder': '000-999',
    'upload_qr_index_duplicate': 'This index already exists',
    'upload_qr_index_invalid': 'Index must be a number from 000 to 999',
    'upload_qr_position_x': 'X',
    'upload_qr_position_y': 'Y',
    'upload_qr_position_z': 'Z',
    'upload_qr_position_invalid': 'Invalid position',
    'upload_qr_pick_position': 'Pick position',
    'upload_qr_pick_active': 'Picking on map...',
    'upload_qr_pick_done': 'Exit picking',
    'upload_qr_pick_hint': 'Click on the 2D map to drop a pin. You can click multiple times until you exit pick mode.',
    'upload_qr_pick_overlay': 'Pick position mode is ON. Other areas are locked.',
    'upload_qr_actions': 'Actions',
    'upload_qr_edit': 'Edit',
    'upload_qr_delete': 'Delete',
    'upload_qr_delete_confirm': 'Are you sure you want to delete this QR code?',
    'upload_qr_save_changes': 'Save',
    'upload_qr_cancel_edit': 'Cancel',
    'upload_qr_edit_position': 'Edit position',
    // Map info translations
    'map_info_title': 'Map information',
    'map_name': 'Map name',
    'map_created_at': 'Created at',
    'map_uploaded_by': 'Uploaded by',
    'map_uploaded_at': 'Uploaded at',
    'map_file_size': 'File size',
    // QR Code descriptions
    'qr_desc_tunnel_start': 'Reference point at tunnel entrance',
    'qr_desc_tunnel_mid': 'Reference point at middle of tunnel',
    'qr_desc_maintenance_area': 'Equipment maintenance area',
    // QR Generator page
    'qr_generator_menu_label': 'QR Code generator',
    'qr_generator_title': 'Generate QR Code',
    'qr_generator_desc': '',
    'qr_generator_index_label': 'Enter index',
    'qr_generator_index_placeholder': 'Enter number from 0 to 999',
    'qr_generator_index_invalid': 'Please enter a valid number from 0 to 999',
    'qr_generator_create_button': 'Generate QR Code',
    'qr_generator_preview_title': 'QR Code preview',
    'qr_generator_no_qr': 'No QR Code generated yet. Please enter an index and click "Generate QR Code".',
    'qr_generator_download_png': 'Download PNG',
    'qr_generator_copy_clipboard': 'Copy to clipboard',
    'qr_generator_copy_success': 'Copied QR Code to clipboard successfully!',
    'qr_generator_copy_error': 'Error copying QR Code to clipboard',
    'qr_generator_reset': 'Reset',
    'qr_generator_qr_content': 'QR Code content',
    // Health page translations
    'health_title': 'Health Check',
    'health_description': 'Check status of frontend and backend services',
    'health_menu_label': 'Health',
    'frontend_health': 'Frontend Health',
    'backend_health': 'Backend Health',
    'backend_services': 'Backend Services',
    'refresh': 'Refresh',
    'checking': 'Checking',
    'degraded': 'Degraded',
    'unhealthy': 'Unhealthy',
    'version': 'Version',
    'url': 'URL',
    'service': 'Service',
    'uptime': 'Uptime',
    'latency': 'Latency',
    'broker': 'Broker',
    'last_updated': 'Last updated',
    // PCD Clipping translations
    'pcd_adjust_point_cloud': 'Adjust point cloud',
    'pcd_close': 'Close',
    'pcd_show_adjust': 'Show point cloud adjustment',
    'pcd_adjust': 'Adjust PCD',
    'pcd_loading': 'Loading point cloud data...',
    'pcd_adjust_display_area': 'Adjust display area',
    'pcd_slider_hint': 'Drag sliders to crop point cloud along X, Y, Z axes',
    'pcd_axis_x': 'X axis:',
    'pcd_axis_y': 'Y axis:',
    'pcd_axis_z': 'Z axis:',
    'pcd_value': 'Value:',
    'pcd_to': 'to',
    'pcd_bounds_x': 'Bounds X:',
    'pcd_bounds_y': 'Bounds Y:',
    'pcd_bounds_z': 'Bounds Z:',
    'pcd_no_pcd_available': 'No PCD available',
    'pcd_x_range': 'X Range:',
    'pcd_y_range': 'Y Range:',
    'pcd_z_range': 'Z Range:',
    'pcd_points_rendered': 'points rendered',
    'pcd_bounds': 'Bounds:',
    'pcd_current_range': 'Current Range:',
    'pcd_loading_point_cloud': 'Loading point cloud...',
    'pcd_no_data': 'No point cloud data',
    'pcd_current_viewing_title': 'Viewing PCD',
    'pcd_uploaded_by': 'Uploaded by',
    'pcd_size': 'Size',
    'pcd_id': 'ID',
    'loading_pcd': 'Loading PCD...',
    'pcd_loaded': 'PCD loaded',
    'no_pcd_loaded': 'No point cloud loaded',
  },
  ja: {
    'language': '言語',
    'vehicles': '車両',
    'about': '概要',
    'map': '追跡',
    'user': 'ユーザー',
    'switch_language': '言語切り替え',
    'help': 'ヘルプ',
    // Vehicles page translations
    'vehicle_list': '車両一覧',
    'vehicle_management': 'トンネル掘削工事車両の管理',
    'total_vehicles': '総車両数',
    'active_vehicles': '稼働中',
    'maintenance': 'メンテナンス',
    'issues': '問題',
    'license_plate': 'ナンバープレート',
    'driver': '運転手',
    'vehicle_type': '役割',
    'vehicle_type_label': '役割:',
    'vehicle_category': '設備カテゴリー',
    'equipment_category_label': '設備カテゴリー:',
    'vehicle_type_unknown': '不明',
    'mission': '任務',
    'status': 'ステータス',
    'actions': '操作',
    'active': '稼働中',
    'confirm_delete': 'この車両を削除してもよろしいですか？',
    'license_plate_required': 'ナンバープレートは必須です',
    'driver_required': '運転手名は必須です',
    'vehicle_type_required': '車両タイプは必須です',
    'mission_required': '任務は必須です',
    'select_vehicle_type': '車両タイプを選択',
    'select_mission': '任務を選択',
    'cancel': 'キャンセル',
    'inactive': '非稼働',
    'driver_placeholder': '運転手名',
    // Vehicle types
    'tbm_tunnel': 'TBMトンネル掘削車',
    'transport_vehicle': '運搬車',
    'concrete_pump': 'コンクリートポンプ車',
    'crane': 'クレーン車',
    'loader': 'ローダー車',
    'truck': 'トラック',
    'other_specialized': 'その他の特殊車両',
    // Mission types
    'tunnel_line_1': 'トンネル路線1掘削',
    'tunnel_line_2': 'トンネル路線2掘削',
    'material_transport': '資材運搬',
    'concrete_wall_pump': 'トンネル壁コンクリート打設',
    'soil_transport': '土砂運搬',
    'equipment_installation': '設備設置',
    'tunnel_maintenance': 'トンネル保守',
    'geological_survey': '地質調査',
    'other_mission': 'その他の任務',
    // VehicleMap page translations
    'vehicle_map_3d': '3D車両マップ',
    'track_real_time': 'トンネル内の車両のリアルタイム位置追跡',
    'fullscreen': '全画面表示',
    'exit_fullscreen': '全画面表示を終了',
    'vehicle_list_title': '車両一覧',
    'filter_vehicles': '車両フィルター',
    'search_vehicle': '車両を検索...',
    'active_vehicles_count': '稼働中',
    'maintenance_vehicles_count': 'メンテナンス',
    'inactive_vehicles_count': '非稼働',
    'total_vehicles_count': '総車両数',
    'legend': '凡例',
    'online': 'オンライン',
    'offline': 'オフライン',
    'offline_vehicles': 'オフライン車両',
    'offline_vehicles_count': 'オフライン',
    'vehicle_info': '車両情報',
    'vehicle_details': '車両詳細',
    'license_plate_label': 'ナンバープレート:',
    'vehicle_type_label': '役割:',
    'status_label': 'ステータス:',
    'driver_info': '運転手情報',
    'driver_name': '氏名:',
    'id_label': 'ID:',
    'mission_type': '任務タイプ',
    'mission_label': '任務:',
    'position_time': '位置・時間',
    'coordinates': '座標:',
    'update_time': '更新:',
    'focus_camera': 'カメラフォーカス',
    'deselect': '選択解除',
    'filter_applied': '適用中のフィルター:',
    'clear_all': 'すべてクリア',
    'status_filter': 'ステータス:',
    'vehicle_type_filter': '役割:',
    'mission_filter': '任務:',
    'filter_popup_title': '車両フィルター',
    'all': 'すべて',
    'clear_filter': 'フィルタークリア',
    'apply_filter': '適用',
    'guide_text': 'ガイド: 右側のリストから車両を選択するか、',
    'guide_text_2d': '2D',
    'guide_text_3d': '3D',
    'guide_text_end': 'マップ内の車両を直接クリックして詳細情報を表示。2D/3D切り替えボタンで視点を変更。',
    'driver_label': '運転手:',
    'type_label': 'タイプ:',
    'mission_label_short': '任務:',
    'status_label_short': 'ステータス:',
    'update_label': '更新:',
    // Driver names
    'driver_name_1': 'グエン・バン・A',
    'driver_name_2': 'チャン・ティ・B',
    'driver_name_3': 'レ・バン・C',
    'driver_name_4': 'ファム・バン・D',
    // EditVehicle page translations
    'edit_vehicle_title': '車両編集',
    'update_vehicle_info': '建設車両の情報を更新',
    'vehicle_not_found': '車両が見つかりません！',
    'update_success': '車両の更新が完了しました！',
    'update_button': '更新',
    // About page translations
    'about_hero_title': 'NishioT&M 車両位置管理システム',
    'about_hero_desc': 'トンネルや鉱山などGPS、GNSSが使用できない環境での車両の管理と追跡のためのシステムです。このシステムはリアルタイム追跡、車両の運行状況の確認等、車両の位置管理を詳細に行うことができます。',
    'about_video_title': 'プロジェクト紹介',
    'about_video_desc': 'デモ動画を見てプロジェクトについて詳しく知りましょう',
    'about_video_alt': 'お使いのブラウザは動画をサポートしていません。',
    'about_mission_title': '私たちのミッション',
    'about_mission_desc': 'トンネルや鉱山などGPS、GNSSが使用できない環境での車両の管理と追跡のための包括的なテクノロジーソリューションを提供できるため',
    'about_mission_1': '安全性、効率性、運用プロセスの最適化を実現します',
    'about_mission_2': '運用効率の最適化',
    'about_mission_3': 'リスクとトラブルの最小化',
    'about_mission_safety': '安全性と効率性',
    // Login page translations
    'login_to_vehicles': '車両システムにログイン',
    'enter_password_to_access': 'アクセスするにはパスワードを入力してください',
    'password': 'パスワード',
    'enter_password': 'パスワードを入力',
    'incorrect_password': 'パスワードが正しくありません',
    'login': 'ログイン',
    'logging_in': 'ログイン中...',
    'default_password': 'デフォルトパスワード',
    'logout': 'ログアウト',
    // Upload page
    'upload_menu_label': 'アップロード',
    'upload_page_title': 'ZIPファイルからマップをアップロード',
    'upload_page_desc': 'スキャン済みデータ（PCD、2D画像、QRコード一覧）を含むZIPパッケージをアップロードし、利用前にプレビューします。',
    'upload_zip_title': 'マップZIPファイルのアップロード',
    'upload_pcd_preview_title': 'PCDプレビュー',
    'upload_pcd_preview_mock': 'PCDプレビュー - 直近ZIPを読み込むとデータが表示されます。',
    'upload_image_preview_title': '2D画像プレビュー',
    'upload_image_preview_mock': '2D画像プレビュー - 直近ZIPを読み込むとデータが表示されます。',
    'upload_qr_list_title': 'QRコード一覧',
    'upload_qr_list_desc': 'ZIPデータから擬似的に抽出されたQRコード一覧です。各QRコードはトンネル内の位置に紐づきます。',
    'upload_qr_code': 'QRコード',
    'upload_qr_position': '位置',
    'upload_qr_empty': 'QRコードがまだ登録されていません。',
    'upload_qr_add_new': '新規データ追加',
    'upload_qr_save': '保存',
    'upload_qr_cancel': 'キャンセル',
    'upload_qr_index_label': 'インデックス',
    'upload_qr_index_placeholder': '000-999',
    'upload_qr_index_duplicate': 'このインデックスは既に存在します',
    'upload_qr_index_invalid': 'インデックスは000から999までの数字である必要があります',
    'upload_qr_position_x': 'X',
    'upload_qr_position_y': 'Y',
    'upload_qr_position_z': 'Z',
    'upload_qr_position_invalid': '位置が無効です',
    'upload_qr_pick_position': '位置を選択',
    'upload_qr_pick_active': 'マップで選択中...',
    'upload_qr_pick_done': '選択を終了',
    'upload_qr_pick_hint': '2Dマップをクリックしてピンを置きます。終了するまで何度でもクリックできます。',
    'upload_qr_pick_overlay': '位置選択モード中です。他の領域はロックされています。',
    'upload_qr_actions': '操作',
    'upload_qr_edit': '編集',
    'upload_qr_delete': '削除',
    'upload_qr_delete_confirm': 'このQRコードを削除してもよろしいですか？',
    'upload_qr_save_changes': '保存',
    'upload_qr_cancel_edit': 'キャンセル',
    'upload_qr_edit_position': '位置を編集',
    // Map info translations
    'map_info_title': 'マップ情報',
    'map_name': 'マップ名',
    'map_created_at': '作成日',
    'map_uploaded_by': 'アップロード者',
    'map_uploaded_at': 'アップロード日',
    'map_file_size': 'ファイルサイズ',
    // QR Code descriptions
    'qr_desc_tunnel_start': 'トンネル入口の基準点',
    'qr_desc_tunnel_mid': 'トンネル中間の基準点',
    'qr_desc_maintenance_area': '設備メンテナンスエリア',
    // QR Generator page
    'qr_generator_menu_label': 'QRコード生成',
    'qr_generator_title': 'QRコード生成',
    'qr_generator_desc': '',
    'qr_generator_index_label': 'インデックス（000-999）',
    'qr_generator_index_placeholder': '0から999までの数字を入力',
    'qr_generator_index_invalid': '0から999までの有効な数字を入力してください',
    'qr_generator_create_button': 'QRコード生成',
    'qr_generator_preview_title': 'QRコードプレビュー',
    'qr_generator_no_qr': 'QRコードがまだ生成されていません。インデックスを入力して「QRコード生成」をクリックしてください。',
    'qr_generator_download_png': 'PNGダウンロード',
    'qr_generator_copy_clipboard': 'クリップボードにコピー',
    'qr_generator_copy_success': 'QRコードをクリップボードにコピーしました！',
    'qr_generator_copy_error': 'QRコードのクリップボードへのコピーに失敗しました',
    'qr_generator_reset': 'リセット',
    'qr_generator_qr_content': 'QRコード内容',
    // Health page translations
    'health_title': 'ヘルスチェック',
    'health_description': 'フロントエンドとバックエンドサービスの状態を確認',
    'health_menu_label': 'ヘルス',
    'frontend_health': 'フロントエンドヘルス',
    'backend_health': 'バックエンドヘルス',
    'backend_services': 'バックエンドサービス',
    'refresh': '更新',
    'checking': '確認中',
    'degraded': '劣化',
    'unhealthy': '不健康',
    'version': 'バージョン',
    'url': 'URL',
    'service': 'サービス',
    'uptime': '稼働時間',
    'latency': 'レイテンシ',
    'broker': 'ブローカー',
    'last_updated': '最終更新',
    // PCD Clipping translations
    'pcd_adjust_point_cloud': 'ポイントクラウド調整',
    'pcd_close': '閉じる',
    'pcd_show_adjust': 'ポイントクラウド調整を表示',
    'pcd_adjust': 'PCD調整',
    'pcd_loading': 'ポイントクラウドデータを読み込み中...',
    'pcd_adjust_display_area': '表示領域の調整',
    'pcd_slider_hint': 'スライダーをドラッグしてX、Y、Z軸に沿ってポイントクラウドを切り取る',
    'pcd_axis_x': 'X軸:',
    'pcd_axis_y': 'Y軸:',
    'pcd_axis_z': 'Z軸:',
    'pcd_value': '値:',
    'pcd_to': 'から',
    'pcd_bounds_x': '範囲X:',
    'pcd_bounds_y': '範囲Y:',
    'pcd_bounds_z': '範囲Z:',
    'pcd_no_pcd_available': 'PCDがありません',
    'pcd_x_range': 'X範囲:',
    'pcd_y_range': 'Y範囲:',
    'pcd_z_range': 'Z範囲:',
    'pcd_points_rendered': 'ポイントをレンダリング',
    'pcd_bounds': '範囲:',
    'pcd_current_range': '現在の範囲:',
    'pcd_loading_point_cloud': 'ポイントクラウドを読み込み中...',
    'pcd_no_data': 'ポイントクラウドデータがありません',
    'pcd_current_viewing_title': 'PCDを表示中',
    'pcd_uploaded_by': 'アップロード者',
    'pcd_size': 'ファイルサイズ',
    'pcd_id': 'ID',
    'loading_pcd': 'PCDを読み込み中...',
    'pcd_loaded': 'PCDを読み込みました',
    'no_pcd_loaded': 'ポイントクラウドデータがまだ読み込まれていません',
  }
};

// Cookie utilities
const getCookie = (name: string): string | null => {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop()?.split(';').shift() || null;
  return null;
};

const setCookie = (name: string, value: string, days: number = 365): void => {
  const expires = new Date();
  expires.setTime(expires.getTime() + (days * 24 * 60 * 60 * 1000));
  document.cookie = `${name}=${value};expires=${expires.toUTCString()};path=/`;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('vi');

  useEffect(() => {
    // Load language from cookie on mount
    const savedLanguage = getCookie('language') as Language;
    if (savedLanguage && (savedLanguage === 'vi' || savedLanguage === 'ja' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    setCookie('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 